# Generated by Django 5.2.4 on 2026-03-02 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about/')),
                ('name', models.CharField(default='Ali Hassan', max_length=100)),
                ('role', models.CharField(default='Python Developer', max_length=100)),
                ('email', models.EmailField(default='your-email@example.com', max_length=254)),
                ('phone', models.CharField(default='+1234567890', max_length=20)),
                ('location', models.CharField(default='City, Country', max_length=200)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'About Me',
                'verbose_name_plural': 'About Me',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('link_live', models.URLField(blank=True, help_text='Live project URL', null=True)),
                ('link_github', models.URLField(blank=True, help_text='GitHub repository URL', null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Projects with lower numbers appear first.')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(help_text='Enter a value between 1 and 100', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('category', models.CharField(choices=[('FRONTEND', 'Frontend Development'), ('BACKEND', 'Backend & Tools')], default='PYTHON', max_length=10)),
            ],
        ),
    ]
