# Generated by Django 6.0.2 on 2026-03-03 13:25

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ali Hassan', max_length=100)),
                ('role', models.CharField(default='Python Developer', max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('projects_completed', models.CharField(blank=True, default='50+', max_length=20, null=True)),
                ('experience_title', models.CharField(blank=True, default='Python Developer', max_length=100, null=True)),
                ('experience_years', models.CharField(blank=True, default='1+ Years', max_length=50, null=True)),
                ('experience_description', models.TextField(blank=True, null=True)),
                ('education_degree', models.CharField(blank=True, default='B.Sc. Computer Science', max_length=100, null=True)),
                ('education_university', models.CharField(blank=True, default='Tech University', max_length=100, null=True)),
                ('education_year', models.CharField(blank=True, default='2020-2024', max_length=50, null=True)),
                ('email', models.EmailField(default='your-email@example.com', max_length=254)),
                ('phone', models.CharField(default='+1234567890', max_length=20)),
                ('location', models.CharField(default='City, Country', max_length=200)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'About Me',
                'verbose_name_plural': 'About Me Settings',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='project_image')),
                ('date', models.DateField(blank=True, null=True)),
                ('tech_stack', models.CharField(blank=True, help_text='Enter skills separated by commas (e.g. Django, React, TailWind)', max_length=255)),
                ('link_live', models.URLField(blank=True, help_text='Live project URL', null=True)),
                ('link_github', models.URLField(blank=True, help_text='GitHub repository URL', null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(help_text='Enter a value between 1 and 100', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('category', models.CharField(choices=[('FRONTEND', 'Frontend Development'), ('BACKEND', 'Backend & Tools')], default='FRONTEND', max_length=10)),
            ],
        ),
    ]
