# Generated by Django 5.2.4 on 2026-03-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Image for the About section', null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='about',
            name='education_degree',
            field=models.CharField(default='B.Sc. Computer Science', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='education_university',
            field=models.CharField(default='Tech University', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='education_year',
            field=models.CharField(default='2018-2022', max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='experience_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='experience_title',
            field=models.CharField(default='Senior Developer', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='experience_years',
            field=models.CharField(default='3+ Years', max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='footer_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='projects_completed',
            field=models.CharField(default='50+', max_length=20),
        ),
        migrations.AddField(
            model_name='about',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
        migrations.AddField(
            model_name='about',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='Enter skills separated by commas (e.g. Django, React, TailWind)', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('FRONTEND', 'Frontend Development'), ('BACKEND', 'Backend & Tools')], default='FRONTEND', max_length=10),
        ),
    ]
