# Generated by Django 5.2.4 on 2026-03-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about_about_image_about_education_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='footer_description',
        ),
        migrations.AlterField(
            model_name='about',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='education_degree',
            field=models.CharField(blank=True, default='B.Sc. Computer Science', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='education_university',
            field=models.CharField(blank=True, default='Tech University', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='education_year',
            field=models.CharField(blank=True, default='2020-2024', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='experience_title',
            field=models.CharField(blank=True, default='Python Developer', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='experience_years',
            field=models.CharField(blank=True, default='1+ Years', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='projects_completed',
            field=models.CharField(blank=True, default='50+', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
