# Generated by Django 5.2.4 on 2026-03-03 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_about_footer_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About Me', 'verbose_name_plural': 'About Me Settings'},
        ),
    ]
